<a id="inicio"></a>
<br><br><br>
<div align="left">
<h1><font size=6>Pandas</font></h1>
    <h2><font color="#5E5E5E" size=5>Ejercicios I</h2>
<br><br><br><br>
</div>


<div align="right">
<font color="#B51700" size=4><b>Análisis y visualización de datos</b></font><br><br>
<font  size=3>Máster Universitario en Ingeniería Informática</font><br>
<font  size=3>Máster Universitario en Big Data y Computación en la Nube</font><br>
<font size=3>Máster Universitario en Inteligencia Artificial</font><br><br>
<font color="#5E5E5E" size=3><b>Luis de la Ossa  &nbsp;&nbsp;</b></font><span style="background-color:#B51700; color:white; padding:2px 6px; font-family:Arial, sans-serif;font-weight:bold;font-size:18px;">UCLM</span>
</div>

---

<a id="indice"></a>
<h2><font color="#5E5E5E" size=5>Índice</font></h2>


* [2. Lectura, escritura e inspeccion de *DataFrames*](#section2)
    * [2.1 Lectura y escritura de *DataFrames*](#section21)
    * [2.2 Inspección del *DataFrame*](#section22)
* [3. Acciones sobre la estructura de un *DataFrame*](#section3)
* [5. Acceso a datos](#section5) 
* [7. Operaciones sobre elementos: transformación](#section7)
    * [7.1 Operaciones sobre *Series*: vectorización](#section71)
    * [7.2 Operaciones vectorizadas sobre *Series* de *Strings*: `Series.str`](#section72)    
    * [7.3 Operaciones de transformación sobre *Series*](#section73)      
    * [7.4 Operaciones de transformación sobre *DataFrames*](#section74)      
* [8. Funciones sobre conjuntos de datos: agregación](#section8)
    * [8.1 Funciones resumen y estadísticas en *Series*](#section81)
    * [8.2 Funciones resumen en *DataFrames*](#section82)
    * [8.3 Agregación en *Series* y *DataFrames*](#section83)

---

In [70]:
import pandas as pd
import numpy as np



<a id="section2"></a>
## <font color="#5E5E5E" size=5> 2. Lectura, escritura e inspeccion de *DataFrames* </font>


<a id="section21"></a> 
### <font color="#5E5E5E">2.1 Lectura y escritura de *DataFrames*</font>

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 1</font> 

Leer el archivo de datos `data/marketing_campaign.csv` y almacenar el contenido en un *DataFrame* denominado `df_marketing`. Especificar que las columnas de cada fila aparecen separadas mediante un tabulador (`'\t'`) y que los tipos de las columnas `Education`, `Marital_Status` y `DT_Customer`, deben ser `string`. Mostrar la cabecera del *DataFrame*.

In [71]:
df_marketing = pd.read_csv("data/marketing_campaign.csv", header=[0], sep="\t",  dtype={"Education": str, "Marital_Status": str, "Dt_Customer": str})
df_marketing

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 2</font> 

Exportar la cabecera del *DataFrame* `df_marketing` a un objeto JSON denominado `json_marketing`. Utilizar el parámetro `orient='records'` para determinar el formato. Acceder al campo `Income` del primer elemento del objeto `json_marketing`.

<div class="alert alert-block alert-info">

<i class="fa fa-info-circle" aria-hidden="true"></i>
Veréis JSON con detalle en el segundo módulo. No obstante, la estructura resultante es una anidación de listas, diccionarios y escalares, por lo que debéis ser capaces de manejarla. Por otra parte, sería buena idea probar los distintos valores que puede tomar `orient` y comprobar los formatos del objeto resultante.

</div>

In [72]:
import json

json_marketing = df_marketing.to_json(orient="records")

json_marketing

'[{"ID":5524,"Year_Birth":1957,"Education":"Graduation","Marital_Status":"Single","Income":58138.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"04-09-2012","Recency":58,"MntWines":635,"MntFruits":88,"MntMeatProducts":546,"MntFishProducts":172,"MntSweetProducts":88,"MntGoldProds":88,"NumDealsPurchases":3,"NumWebPurchases":8,"NumCatalogPurchases":10,"NumStorePurchases":4,"NumWebVisitsMonth":7,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":1},{"ID":2174,"Year_Birth":1954,"Education":"Graduation","Marital_Status":"Single","Income":46344.0,"Kidhome":1,"Teenhome":1,"Dt_Customer":"08-03-2014","Recency":38,"MntWines":11,"MntFruits":1,"MntMeatProducts":6,"MntFishProducts":2,"MntSweetProducts":1,"MntGoldProds":6,"NumDealsPurchases":2,"NumWebPurchases":1,"NumCatalogPurchases":1,"NumStorePurchases":2,"NumWebVisitsMonth":5,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":4141,"Year_Birth":1965,"Education":"Graduation","Marital_Status":"Together","Income":71613.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"21-08-2013","Recency":26,"MntWines":426,"MntFruits":49,"MntMeatProducts":127,"MntFishProducts":111,"MntSweetProducts":21,"MntGoldProds":42,"NumDealsPurchases":1,"NumWebPurchases":8,"NumCatalogPurchases":2,"NumStorePurchases":10,"NumWebVisitsMonth":4,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":6182,"Year_Birth":1984,"Education":"Graduation","Marital_Status":"Together","Income":26646.0,"Kidhome":1,"Teenhome":0,"Dt_Customer":"10-02-2014","Recency":26,"MntWines":11,"MntFruits":4,"MntMeatProducts":20,"MntFishProducts":10,"MntSweetProducts":3,"MntGoldProds":5,"NumDealsPurchases":2,"NumWebPurchases":2,"NumCatalogPurchases":0,"NumStorePurchases":4,"NumWebVisitsMonth":6,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":5324,"Year_Birth":1981,"Education":"PhD","Marital_Status":"Married","Income":58293.0,"Kidhome":1,"Teenhome":0,"Dt_Customer":"19-01-2014","Recency":94,"MntWines":173,"MntFruits":43,"MntMeatProducts":118,"MntFishProducts":46,"MntSweetProducts":27,"MntGoldProds":15,"NumDealsPurchases":5,"NumWebPurchases":5,"NumCatalogPurchases":3,"NumStorePurchases":6,"NumWebVisitsMonth":5,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":7446,"Year_Birth":1967,"Education":"Master","Marital_Status":"Together","Income":62513.0,"Kidhome":0,"Teenhome":1,"Dt_Customer":"09-09-2013","Recency":16,"MntWines":520,"MntFruits":42,"MntMeatProducts":98,"MntFishProducts":0,"MntSweetProducts":42,"MntGoldProds":14,"NumDealsPurchases":2,"NumWebPurchases":6,"NumCatalogPurchases":4,"NumStorePurchases":10,"NumWebVisitsMonth":6,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":965,"Year_Birth":1971,"Education":"Graduation","Marital_Status":"Divorced","Income":55635.0,"Kidhome":0,"Teenhome":1,"Dt_Customer":"13-11-2012","Recency":34,"MntWines":235,"MntFruits":65,"MntMeatProducts":164,"MntFishProducts":50,"MntSweetProducts":49,"MntGoldProds":27,"NumDealsPurchases":4,"NumWebPurchases":7,"NumCatalogPurchases":3,"NumStorePurchases":7,"NumWebVisitsMonth":6,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":6177,"Year_Birth":1985,"Education":"PhD","Marital_Status":"Married","Income":33454.0,"Kidhome":1,"Teenhome":0,"Dt_Customer":"08-05-2013","Recency":32,"MntWines":76,"MntFruits":10,"MntMeatProducts":56,"MntFishProducts":3,"MntSweetProducts":1,"MntGoldProds":23,"NumDealsPurchases":2,"NumWebPurchases":4,"NumCatalogPurchases":0,"NumStorePurchases":4,"NumWebVisitsMonth":8,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":4855,"Year_Birth":1974,"Education":"PhD","Marital_Status":"Together","Income":30351.0,"Kidhome":1,"Teenhome":0,"Dt_Customer":"06-06-2013","Recency":19,"MntWines":14,"MntFruits":0,"MntMeatProducts":24,"MntFishProducts":3,"MntSweetProducts":3,"MntGoldProds":2,"NumDealsPurchases":1,"NumWebPurchases":3,"NumCatalogPurchases":0,"NumStorePurchases":2,"NumWebVisitsMonth":9,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":1},{"ID":5899,"Year_Birth":1950,"Education":"PhD","Marital_Status":"Together","Income":5648.0,"Kidhome":1,"Teenhome":1,"Dt_Customer":"13-03-2014","Recency":68,"MntWines":28,"MntFruits":0,"MntMeatProducts":6,"MntFishProducts":1,"MntSweetProducts":1,"MntGoldProds":13,"NumDealsPurchases":1,"NumWebPurchases":1,"NumCatalogPurchases":0,"NumStorePurchases":0,"NumWebVisitsMonth":20,"AcceptedCmp3":1,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":1994,"Year_Birth":1983,"Education":"Graduation","Marital_Status":"Married","Income":null,"Kidhome":1,"Teenhome":0,"Dt_Customer":"15-11-2013","Recency":11,"MntWines":5,"MntFruits":5,"MntMeatProducts":6,"MntFishProducts":0,"MntSweetProducts":2,"MntGoldProds":1,"NumDealsPurchases":1,"NumWebPurchases":1,"NumCatalogPurchases":0,"NumStorePurchases":2,"NumWebVisitsMonth":7,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":387,"Year_Birth":1976,"Education":"Basic","Marital_Status":"Married","Income":7500.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"13-11-2012","Recency":59,"MntWines":6,"MntFruits":16,"MntMeatProducts":11,"MntFishProducts":11,"MntSweetProducts":1,"MntGoldProds":16,"NumDealsPurchases":1,"NumWebPurchases":2,"NumCatalogPurchases":0,"NumStorePurchases":3,"NumWebVisitsMonth":8,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":2125,"Year_Birth":1959,"Education":"Graduation","Marital_Status":"Divorced","Income":63033.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"15-11-2013","Recency":82,"MntWines":194,"MntFruits":61,"MntMeatProducts":480,"MntFishProducts":225,"MntSweetProducts":112,"MntGoldProds":30,"NumDealsPurchases":1,"NumWebPurchases":3,"NumCatalogPurchases":4,"NumStorePurchases":8,"NumWebVisitsMonth":2,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":8180,"Year_Birth":1952,"Education":"Master","Marital_Status":"Divorced","Income":59354.0,"Kidhome":1,"Teenhome":1,"Dt_Customer":"15-11-2013","Recency":53,"MntWines":233,"MntFruits":2,"MntMeatProducts":53,"MntFishProducts":3,"MntSweetProducts":5,"MntGoldProds":14,"NumDealsPurchases":3,"NumWebPurchases":6,"NumCatalogPurchases":1,"NumStorePurchases":5,"NumWebVisitsMonth":6,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":2569,"Year_Birth":1987,"Education":"Graduation","Marital_Status":"Married","Income":17323.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"10-10-2012","Recency":38,"MntWines":3,"MntFruits":14,"MntMeatProducts":17,"MntFishProducts":6,"MntSweetProducts":1,"MntGoldProds":5,"NumDealsPurchases":1,"NumWebPurchases":1,"NumCatalogPurchases":0,"NumStorePurchases":3,"NumWebVisitsMonth":8,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":2114,"Year_Birth":1946,"Education":"PhD","Marital_Status":"Single","Income":82800.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"24-11-2012","Recency":23,"MntWines":1006,"MntFruits":22,"MntMeatProducts":115,"MntFishProducts":59,"MntSweetProducts":68,"MntGoldProds":45,"NumDealsPurchases":1,"NumWebPurchases":7,"NumCatalogPurchases":6,"NumStorePurchases":12,"NumWebVisitsMonth":3,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":1,"AcceptedCmp1":1,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":1},{"ID":9736,"Year_Birth":1980,"Education":"Graduation","Marital_Status":"Married","Income":41850.0,"Kidhome":1,"Teenhome":1,"Dt_Customer":"24-12-2012","Recency":51,"MntWines":53,"MntFruits":5,"MntMeatProducts":19,"MntFishProducts":2,"MntSweetProducts":13,"MntGoldProds":4,"NumDealsPurchases":3,"NumWebPurchases":3,"NumCatalogPurchases":0,"NumStorePurchases":3,"NumWebVisitsMonth":8,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":4939,"Year_Birth":1946,"Education":"Graduation","Marital_Status":"Together","Income":37760.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"31-08-2012","Recency":20,"MntWines":84,"MntFruits":5,"MntMeatProducts":38,"MntFishProducts":150,"MntSweetProducts":12,"MntGoldProds":28,"NumDealsPurchases":2,"NumWebPurchases":4,"NumCatalogPurchases":1,"NumStorePurchases":6,"NumWebVisitsMonth":7,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":6565,"Year_Birth":1949,"Education":"Master","Marital_Status":"Married","Income":76995.0,"Kidhome":0,"Teenhome":1,"Dt_Customer":"28-03-2013","Recency":91,"MntWines":1012,"MntFruits":80,"MntMeatProducts":498,"MntFishProducts":0,"MntSweetProducts":16,"MntGoldProds":176,"NumDealsPurchases":2,"NumWebPurchases":11,"NumCatalogPurchases":4,"NumStorePurchases":9,"NumWebVisitsMonth":5,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":1,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":2278,"Year_Birth":1985,"Education":"2n Cycle","Marital_Status":"Single","Income":33812.0,"Kidhome":1,"Teenhome":0,"Dt_Customer":"03-11-2012","Recency":86,"MntWines":4,"MntFruits":17,"MntMeatProducts":19,"MntFishProducts":30,"MntSweetProducts":24,"MntGoldProds":39,"NumDealsPurchases":2,"NumWebPurchases":2,"NumCatalogPurchases":1,"NumStorePurchases":3,"NumWebVisitsMonth":6,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":9360,"Year_Birth":1982,"Education":"Graduation","Marital_Status":"Married","Income":37040.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"08-08-2012","Recency":41,"MntWines":86,"MntFruits":2,"MntMeatProducts":73,"MntFishProducts":69,"MntSweetProducts":38,"MntGoldProds":48,"NumDealsPurchases":1,"NumWebPurchases":4,"NumCatalogPurchases":2,"NumStorePurchases":5,"NumWebVisitsMonth":8,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":5376,"Year_Birth":1979,"Education":"Graduation","Marital_Status":"Married","Income":2447.0,"Kidhome":1,"Teenhome":0,"Dt_Customer":"06-01-2013","Recency":42,"MntWines":1,"MntFruits":1,"MntMeatProducts":1725,"MntFishProducts":1,"MntSweetProducts":1,"MntGoldProds":1,"NumDealsPurchases":15,"NumWebPurchases":0,"NumCatalogPurchases":28,"NumStorePurchases":0,"NumWebVisitsMonth":1,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":1993,"Year_Birth":1949,"Education":"PhD","Marital_Status":"Married","Income":58607.0,"Kidhome":0,"Teenhome":1,"Dt_Customer":"23-12-2012","Recency":63,"MntWines":867,"MntFruits":0,"MntMeatProducts":86,"MntFishProducts":0,"MntSweetProducts":0,"MntGoldProds":19,"NumDealsPurchases":3,"NumWebPurchases":2,"NumCatalogPurchases":3,"NumStorePurchases":9,"NumWebVisitsMonth":8,"AcceptedCmp3":0,"AcceptedCmp4":1,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":4047,"Year_Birth":1954,"Education":"PhD","Marital_Status":"Married","Income":65324.0,"Kidhome":0,"Teenhome":1,"Dt_Customer":"11-01-2014","Recency":0,"MntWines":384,"MntFruits":0,"MntMeatProducts":102,"MntFishProducts":21,"MntSweetProducts":32,"MntGoldProds":5,"NumDealsPurchases":3,"NumWebPurchases":6,"NumCatalogPurchases":2,"NumStorePurchases":9,"NumWebVisitsMonth":4,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":1409,"Year_Birth":1951,"Education":"Graduation","Marital_Status":"Together","Income":40689.0,"Kidhome":0,"Teenhome":1,"Dt_Customer":"18-03-2013","Recency":69,"MntWines":270,"MntFruits":3,"MntMeatProducts":27,"MntFishProducts":39,"MntSweetProducts":6,"MntGoldProds":99,"NumDealsPurchases":7,"NumWebPurchases":7,"NumCatalogPurchases":1,"NumStorePurchases":5,"NumWebVisitsMonth":8,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":7892,"Year_Birth":1969,"Education":"Graduation","Marital_Status":"Single","Income":18589.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"02-01-2013","Recency":89,"MntWines":6,"MntFruits":4,"MntMeatProducts":25,"MntFishProducts":15,"MntSweetProducts":12,"MntGoldProds":13,"NumDealsPurchases":2,"NumWebPurchases":2,"NumCatalogPurchases":1,"NumStorePurchases":3,"NumWebVisitsMonth":7,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":2404,"Year_Birth":1976,"Education":"Graduation","Marital_Status":"Married","Income":53359.0,"Kidhome":1,"Teenhome":1,"Dt_Customer":"27-05-2013","Recency":4,"MntWines":173,"MntFruits":4,"MntMeatProducts":30,"MntFishProducts":3,"MntSweetProducts":6,"MntGoldProds":41,"NumDealsPurchases":4,"NumWebPurchases":5,"NumCatalogPurchases":1,"NumStorePurchases":4,"NumWebVisitsMonth":7,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":5255,"Year_Birth":1986,"Education":"Graduation","Marital_Status":"Single","Income":null,"Kidhome":1,"Teenhome":0,"Dt_Customer":"20-02-2013","Recency":19,"MntWines":5,"MntFruits":1,"MntMeatProducts":3,"MntFishProducts":3,"MntSweetProducts":263,"MntGoldProds":362,"NumDealsPurchases":0,"NumWebPurchases":27,"NumCatalogPurchases":0,"NumStorePurchases":0,"NumWebVisitsMonth":1,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":9422,"Year_Birth":1989,"Education":"Graduation","Marital_Status":"Married","Income":38360.0,"Kidhome":1,"Teenhome":0,"Dt_Customer":"31-05-2013","Recency":26,"MntWines":36,"MntFruits":2,"MntMeatProducts":42,"MntFishProducts":20,"MntSweetProducts":21,"MntGoldProds":10,"NumDealsPurchases":2,"NumWebPurchases":2,"NumCatalogPurchases":1,"NumStorePurchases":4,"NumWebVisitsMonth":3,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":1966,"Year_Birth":1965,"Education":"PhD","Marital_Status":"Married","Income":84618.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"22-11-2013","Recency":96,"MntWines":684,"MntFruits":100,"MntMeatProducts":801,"MntFishProducts":21,"MntSweetProducts":66,"MntGoldProds":0,"NumDealsPurchases":1,"NumWebPurchases":6,"NumCatalogPurchases":9,"NumStorePurchases":10,"NumWebVisitsMonth":2,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":1,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":6864,"Year_Birth":1989,"Education":"Master","Marital_Status":"Divorced","Income":10979.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"22-05-2014","Recency":34,"MntWines":8,"MntFruits":4,"MntMeatProducts":10,"MntFishProducts":2,"MntSweetProducts":2,"MntGoldProds":4,"NumDealsPurchases":2,"NumWebPurchases":3,"NumCatalogPurchases":0,"NumStorePurchases":3,"NumWebVisitsMonth":5,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":3033,"Year_Birth":1963,"Education":"Master","Marital_Status":"Together","Income":38620.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"11-05-2013","Recency":56,"MntWines":112,"MntFruits":17,"MntMeatProducts":44,"MntFishProducts":34,"MntSweetProducts":22,"MntGoldProds":89,"NumDealsPurchases":1,"NumWebPurchases":2,"NumCatalogPurchases":5,"NumStorePurchases":3,"NumWebVisitsMonth":3,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":5710,"Year_Birth":1970,"Education":"Graduation","Marital_Status":"Together","Income":40548.0,"Kidhome":0,"Teenhome":1,"Dt_Customer":"10-10-2012","Recency":31,"MntWines":110,"MntFruits":0,"MntMeatProducts":5,"MntFishProducts":2,"MntSweetProducts":0,"MntGoldProds":3,"NumDealsPurchases":2,"NumWebPurchases":2,"NumCatalogPurchases":1,"NumStorePurchases":4,"NumWebVisitsMonth":5,"AcceptedCmp3":0,"AcceptedCmp4":1,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":7373,"Year_Birth":1952,"Education":"PhD","Marital_Status":"Divorced","Income":46610.0,"Kidhome":0,"Teenhome":2,"Dt_Customer":"29-10-2012","Recency":8,"MntWines":96,"MntFruits":12,"MntMeatProducts":96,"MntFishProducts":33,"MntSweetProducts":22,"MntGoldProds":43,"NumDealsPurchases":6,"NumWebPurchases":4,"NumCatalogPurchases":1,"NumStorePurchases":6,"NumWebVisitsMonth":6,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":1},{"ID":8755,"Year_Birth":1946,"Education":"Master","Marital_Status":"Married","Income":68657.0,"Kidhome":0,"Teenhome":0,"Dt_Customer":"20-02-2013","Recency":4,"MntWines":482,"MntFruits":34,"MntMeatProducts":471,"MntFishProducts":119,"MntSweetProducts":68,"MntGoldProds":22,"NumDealsPurchases":1,"NumWebPurchases":3,"NumCatalogPurchases":5,"NumStorePurchases":9,"NumWebVisitsMonth":7,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":10738,"Year_Birth":1951,"Education":"Master","Marital_Status":"Single","Income":49389.0,"Kidhome":1,"Teenhome":1,"Dt_Customer":"29-08-2013","Recency":55,"MntWines":40,"MntFruits":0,"MntMeatProducts":19,"MntFishProducts":2,"MntSweetProducts":1,"MntGoldProds":3,"NumDealsPurchases":1,"NumWebPurchases":2,"NumCatalogPurchases":0,"NumStorePurchases":3,"NumWebVisitsMonth":7,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":4339,"Year_Birth":1970,"Education":"PhD","Marital_Status":"Married","Income":67353.0,"Kidhome":0,"Teenhome":1,"Dt_Customer":"31-12-2013","Recency":37,"MntWines":702,"MntFruits":17,"MntMeatProducts":151,"MntFishProducts":0,"MntSweetProducts":8,"MntGoldProds":35,"NumDealsPurchases":5,"NumWebPurchases":5,"NumCatalogPurchases":6,"NumStorePurchases":12,"NumWebVisitsMonth":2,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":10755,"Year_Birth":1976,"Education":"2n Cycle","Marital_Status":"Married","Income":23718.0,"Kidhome":1,"Teenhome":0,"Dt_Customer":"02-09-2013","Recency":76,"MntWines":6,"MntFruits":3,"MntMeatProducts":14,"MntFishProducts":15,"MntSweetProducts":7,"MntGoldProds":36,"NumDealsPurchases":3,"NumWebPurchases":3,"NumCatalogPurchases":1,"NumStorePurchases":2,"NumWebVisitsMonth":7,"AcceptedCmp3":0,"AcceptedCmp4":0,"AcceptedCmp5":0,"AcceptedCmp1":0,"AcceptedCmp2":0,"Complain":0,"Z_CostContact":3,"Z_Revenue":11,"Response":0},{"ID":8595,"Year_Birth":1973,"Educatio

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 3</font> 

Exportar el *DataFrame* `df_marketing` a un archivo excel denominado `data/marketing.xlsx`,en el que la hoja que contiene los datos se denomine `Datos campaña`, y de modo que no se incluya el índice.

In [73]:
df_marketing.to_excel("data/marketing.xlsx", sheet_name="Datos campaña", index=False)



<a id="section22"></a> 
### <font color="#5E5E5E">2.2 Inspección de un *DataFrame* </font>

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 4</font> 

Visualizar la información sobre la estructura del *DataFrame* `df_marketing`. ¿Existen columnas con valores perdidos? ¿Cuántas?

In [74]:
df_marketing.isna().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 5</font> 

Mostrar, mediante `DataFrame.describe()`, las características resumen de las columas que **no** son numéricas.

In [75]:
df_marketing.describe(exclude=[np.number])

         Education Marital_Status Dt_Customer
count         2240           2240        2240
unique           5              8         663
top     Graduation        Married  31-08-2012
freq          1127            864          12

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 6</font> 

Mostrar, mediante `DataFrame.describe()`, las características resumen de las columas que **sí** son numéricas. Mostrar los cuartiles, es decir, percentiles 25%, 50% y 75%.

In [76]:
df_marketing.describe(include=[np.number], percentiles=[0.25, 0.5, 0.75])

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

<div align="right">
<a href="#indice"><font size=5 color=#B51700><i class="fa fa-arrow-circle-up" aria-hidden="true" ></i></font></a>
</div>


---

<a id="section3"></a> 
## <font color="#5E5E5E">3. Acciones sobre la estructura de un *DataFrame* </font>

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 7</font> 

Establecer como índice del *DataFrame* `df_marketing` la columna `ID`. Hacer la operación sobre el propio *DataFrame* de modo que no se cree una copia, y que no se conserve la columna `ID`.

In [77]:
df_marketing.reset_index(inplace=True)

df_marketing.set_index("ID", inplace=True)

df_marketing

,index,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
ID,,,,,,,,,,,,,,,,,,,,,
5524,0,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
2174,1,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
4141,2,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
6182,3,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
5324,4,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10870,2235,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
4001,2236,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
7270,2237,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
8235,2238,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
9405,2239,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 8</font> 

Cambiar los nombres de las columnas `Year_Birth`, `Education`  y `Marital_Status` del *DataFrame* `df_marketing` a `Año de nacimiento`, `Educación` y `Estado civil`, respectivamente. Devolver una copia del *DataFrame*, de modo que el *DataFrame* original se mantenga inalterado. Utilizar el parámetro `axis` para indicar que se actúa sobre las columnas.

In [78]:
df_marketing_copy = df_marketing.rename(columns={"Year_Birth": "Año_Nacimiento", "Education": "Educación", "Marital_Status": "Estado_Civil"}, inplace=False)
df_marketing_copy

,index,Año_Nacimiento,Educación,Estado_Civil,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
ID,,,,,,,,,,,,,,,,,,,,,
5524,0,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
2174,1,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
4141,2,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
6182,3,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
5324,4,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10870,2235,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
4001,2236,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
7270,2237,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
8235,2238,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
9405,2239,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 9</font> 

Trasformar los valores del índice del *DataFrame* `df_marketing`  multiplicándolos por 10.  Devolver una copia del *DataFrame*, de modo que el *DataFrame* original se mantenga inalterado. Utilizar el parámetro `index` para indicar que se actúa sobre el índice, y una función *lambda*.

In [86]:
df_marketing["index"].apply(lambda x: x*10)

ID
5524         0
2174        10
4141        20
6182        30
5324        40
         ...
10870    22350
4001     22360
7270     22370
8235     22380
9405     22390
Name: index, Length: 2240, dtype: int64

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 10</font> 

Ordenar ascendientemente el *DataFrame* `df_marketing` en función de los valores del índice. Actuar sobre el propio *DataFrame*.

In [92]:
df_marketing.sort_values(by="index", ascending=True, inplace=True)
df_marketing

,index,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
ID,,,,,,,,,,,,,,,,,,,,,
5524,0,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
2174,1,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
4141,2,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
6182,3,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
5324,4,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10870,2235,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
4001,2236,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
7270,2237,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
8235,2238,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
9405,2239,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 11</font> 

Eliminar las columnas `Z_CostContact` y `Z_Revenue` del *DataFrame* `df_marketing`. Actuar sobre el propio *DataFrame*.

In [99]:
df_marketing.drop(columns=["Z_CostContact", "Z_Revenue"], inplace=True)

KeyError: "['Z_CostContact', 'Z_Revenue'] not found in axis"

In [100]:
df_marketing

,index,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response
ID,,,,,,,,,,,,,,,,,,,,,
5524,0,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,10,4,7,0,0,0,0,0,0,1
2174,1,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,1,2,5,0,0,0,0,0,0,0
4141,2,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,2,10,4,0,0,0,0,0,0,0
6182,3,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,0,4,6,0,0,0,0,0,0,0
5324,4,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,3,6,5,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10870,2235,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,3,4,5,0,0,0,0,0,0,0
4001,2236,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,2,5,7,0,0,0,1,0,0,0
7270,2237,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,3,13,6,0,1,0,0,0,0,0
8235,2238,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,5,10,3,0,0,0,0,0,0,0
9405,2239,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,1,4,7,0,0,0,0,0,0,1

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 12</font> 

Eliminar del *DataFrame* `df_marketing` todas las filas que no tengan al menos 24 valores conocidos. Operar sobre el propio *DataFrame*.

In [102]:
df_marketing.dropna(thresh=24, inplace=True)
df_marketing

,index,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response
ID,,,,,,,,,,,,,,,,,,,,,
5524,0,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,10,4,7,0,0,0,0,0,0,1
2174,1,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,1,2,5,0,0,0,0,0,0,0
4141,2,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,2,10,4,0,0,0,0,0,0,0
6182,3,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,0,4,6,0,0,0,0,0,0,0
5324,4,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,3,6,5,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10870,2235,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,3,4,5,0,0,0,0,0,0,0
4001,2236,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,2,5,7,0,0,0,1,0,0,0
7270,2237,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,3,13,6,0,1,0,0,0,0,0
8235,2238,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,5,10,3,0,0,0,0,0,0,0
9405,2239,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,1,4,7,0,0,0,0,0,0,1

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 13</font> 

Cambiar el tipo de datos de las columnas `MntWines`, `MntFruits`, `MntMeatProducts`, `MntFishProducts`, `MntSweetProducts` y `MntGoldProds` *DataFrame* `df_marketing` a `float64`. Devolver una copia pero asignarla al mismo `df_marketing`.

*Nota:* Con algunas versiones de *pandas*, el parámetro `copy` tiene un comportamiento errático.

In [113]:
df_marketing = df_marketing.astype({"MntWines": "float64", "MntFruits": "float64", "MntMeatProducts": "float64", "MntSweetProducts": "float64", "MntGoldProds": "float64"})
df_marketing.dtypes

index                    int64
Year_Birth               int64
Education                  str
Marital_Status             str
Income                 float64
Kidhome                  int64
Teenhome                 int64
Dt_Customer                str
Recency                  int64
MntWines               float64
MntFruits              float64
MntMeatProducts        float64
MntFishProducts          int64
MntSweetProducts       float64
MntGoldProds           float64
NumDealsPurchases        int64
NumWebPurchases          int64
NumCatalogPurchases      int64
NumStorePurchases        int64
NumWebVisitsMonth        int64
AcceptedCmp3             int64
AcceptedCmp4             int64
AcceptedCmp5             int64
AcceptedCmp1             int64
AcceptedCmp2             int64
Complain                 int64
Response                 int64
dtype: object

<div align="right">
<a href="#indice"><font size=5 color=#B51700><i class="fa fa-arrow-circle-up" aria-hidden="true" ></i></font></a>
</div>


---

<a id="section5"></a> 
## <font color="#5E5E5E">5. Acceso a datos </font>

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 14</font> 


Mostrar la columna `Education` del *DataFrame* `df_marketing`.

In [114]:
df_marketing["Education"]

ID
5524     Graduation
2174     Graduation
4141     Graduation
6182     Graduation
5324            PhD
            ...
10870    Graduation
4001            PhD
7270     Graduation
8235         Master
9405            PhD
Name: Education, Length: 2240, dtype: str

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 15</font> 


Mostrar las columnas `Year_Birth`, `Education`, `Marital_Status` e `Income` del *DataFrame* `df_marketing`.

In [117]:
df_marketing[["Year_Birth","Education","Marital_Status","Income"]]

       Year_Birth   Education Marital_Status   Income
ID
5524         1957  Graduation         Single  58138.0
2174         1954  Graduation         Single  46344.0
4141         1965  Graduation       Together  71613.0
6182         1984  Graduation       Together  26646.0
5324         1981         PhD        Married  58293.0
...           ...         ...            ...      ...
10870        1967  Graduation        Married  61223.0
4001         1946         PhD       Together  64014.0
7270         1981  Graduation       Divorced  56981.0
8235         1956      Master       Together  69245.0
9405         1954         PhD        Married  52869.0

[2240 rows x 4 columns]

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 16</font> 


Crear un *DataFrame* denominado `df_personal`, y que contenga las columnas `Year_Birth`, `Education`, `Marital_Status` e `Income` del *DataFrame* `df_marketing`. Mostrar su cabecera.

In [118]:
df_personal = df_marketing[["Year_Birth","Education","Marital_Status","Income"]]

df_personal.head()

      Year_Birth   Education Marital_Status   Income
ID
5524        1957  Graduation         Single  58138.0
2174        1954  Graduation         Single  46344.0
4141        1965  Graduation       Together  71613.0
6182        1984  Graduation       Together  26646.0
5324        1981         PhD        Married  58293.0

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 17</font> 

Acceder y mostrar la fila del *DataFrame* `df_marketing` correspondiente al índice `521`.

In [121]:
df_marketing.loc[521]

index                        1859
Year_Birth                   1985
Education              Graduation
Marital_Status           Together
Income                    54006.0
Kidhome                         1
Teenhome                        0
Dt_Customer            18-09-2012
Recency                        42
MntWines                    174.0
MntFruits                    77.0
MntMeatProducts             203.0
MntFishProducts                 6
MntSweetProducts             24.0
MntGoldProds                 97.0
NumDealsPurchases               2
NumWebPurchases                 8
NumCatalogPurchases             1
NumStorePurchases               7
NumWebVisitsMonth               7
AcceptedCmp3                    0
AcceptedCmp4                    0
AcceptedCmp5                    0
AcceptedCmp1                    0
AcceptedCmp2                    0
Complain                        0
Response                        0
Name: 521, dtype: object

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 18</font> 

La lista `smallest_indices` contiene los valores del índice que son menores que 50. Mostrar un *DataFrame* con las filas del *DataFrame* `df_marketing` correspondientes a esos valores.

In [134]:
smallest_indices = df_marketing.index[df_marketing.index < 50].tolist()
df_marketing.loc[smallest_indices]

,index,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response
ID,,,,,,,,,,,,,,,,,,,,,
0,214,1985,Graduation,Married,70951.0,0,0,04-05-2013,66,239.0,...,4,9,1,0,0,0,0,0,0,0
22,491,1976,Graduation,Divorced,46310.0,1,0,03-12-2012,99,185.0,...,1,5,8,0,0,0,0,0,0,0
35,524,1987,Graduation,Married,25545.0,1,0,08-09-2012,35,32.0,...,2,3,6,0,0,0,0,0,0,1
20,768,1965,2n Cycle,Married,46891.0,0,1,01-09-2013,91,43.0,...,1,4,4,0,0,0,0,0,0,0
49,782,1970,Graduation,Single,20587.0,1,0,11-05-2014,39,2.0,...,1,2,7,0,0,0,0,0,0,0
1,822,1961,Graduation,Single,57091.0,0,0,15-06-2014,0,464.0,...,3,7,5,0,0,0,0,1,0,1
25,1474,1958,Graduation,Married,65148.0,0,1,16-11-2012,9,460.0,...,6,7,4,0,0,0,0,0,0,0
9,1511,1975,Master,Single,46098.0,1,1,18-08-2012,86,57.0,...,2,2,8,0,0,0,0,0,0,0
24,1596,1960,Master,Together,17144.0,1,1,15-02-2014,96,18.0,...,0,4,7,0,0,0,0,0,0,0
13,1654,1947,PhD,Widow,25358.0,0,1,22-07-2013,57,19.0,...,0,3,6,0,0,0,0,0,0,0
48,1740,1964,Graduation,Together,55761.0,0,1,24-04-2014,97,136.0,...,1,3,6,0,1,0,0,0,0,0
17,1906,1971,PhD,Married,60491.0,0,1,06-09-2013,81,637.0,...,11,7,5,0,0,0,0,0,0,0

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 19</font> 

Repetir el ejercicio anterior, pero mostrando las filas correspondientes a los índices menores que 50 utilizando *slicing*.

In [130]:

df_marketing_ordenado = df_marketing.sort_index()


smallest_indices = df_marketing_ordenado.index[df_marketing_ordenado.index < 50].tolist()

df_marketing_ordenado.loc[smallest_indices[0]:smallest_indices[-1]]

,index,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response
ID,,,,,,,,,,,,,,,,,,,,,
0,214,1985,Graduation,Married,70951.0,0,0,04-05-2013,66,239.0,...,4,9,1,0,0,0,0,0,0,0
1,822,1961,Graduation,Single,57091.0,0,0,15-06-2014,0,464.0,...,3,7,5,0,0,0,0,1,0,1
9,1511,1975,Master,Single,46098.0,1,1,18-08-2012,86,57.0,...,2,2,8,0,0,0,0,0,0,0
13,1654,1947,PhD,Widow,25358.0,0,1,22-07-2013,57,19.0,...,0,3,6,0,0,0,0,0,0,0
17,1906,1971,PhD,Married,60491.0,0,1,06-09-2013,81,637.0,...,11,7,5,0,0,0,0,0,0,0
20,768,1965,2n Cycle,Married,46891.0,0,1,01-09-2013,91,43.0,...,1,4,4,0,0,0,0,0,0,0
22,491,1976,Graduation,Divorced,46310.0,1,0,03-12-2012,99,185.0,...,1,5,8,0,0,0,0,0,0,0
24,1596,1960,Master,Together,17144.0,1,1,15-02-2014,96,18.0,...,0,4,7,0,0,0,0,0,0,0
25,1474,1958,Graduation,Married,65148.0,0,1,16-11-2012,9,460.0,...,6,7,4,0,0,0,0,0,0,0
35,524,1987,Graduation,Married,25545.0,1,0,08-09-2012,35,32.0,...,2,3,6,0,0,0,0,0,0,1
48,1740,1964,Graduation,Together,55761.0,0,1,24-04-2014,97,136.0,...,1,3,6,0,1,0,0,0,0,0
49,782,1970,Graduation,Single,20587.0,1,0,11-05-2014,39,2.0,...,1,2,7,0,0,0,0,0,0,0

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 20</font> 

Repetir el ejercicio anterior, pero accediendo solamente a las columnas `Year_Birth`, `Education`, `Marital_Status` e `Income` del *DataFrame* `df_marketing`.

In [131]:
df_marketing_ordenado[["Year_Birth","Education","Marital_Status","Income"]].loc[smallest_indices[0]:smallest_indices[-1]]

    Year_Birth   Education Marital_Status   Income
ID
0         1985  Graduation        Married  70951.0
1         1961  Graduation         Single  57091.0
9         1975      Master         Single  46098.0
13        1947         PhD          Widow  25358.0
17        1971         PhD        Married  60491.0
20        1965    2n Cycle        Married  46891.0
22        1976  Graduation       Divorced  46310.0
24        1960      Master       Together  17144.0
25        1958  Graduation        Married  65148.0
35        1987  Graduation        Married  25545.0
48        1964  Graduation       Together  55761.0
49        1970  Graduation         Single  20587.0

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 21</font> 

Mostrar un *DataFrame* con los valores de `Year_Birth`, `Education`, `Marital_Status` e `Income` de posiciones del 5 a 10 del *DataFrame* `df_marketing`.

In [136]:
df_marketing_ordenado[["Year_Birth","Education","Marital_Status","Income"]][5:10]

    Year_Birth   Education Marital_Status   Income
ID
20        1965    2n Cycle        Married  46891.0
22        1976  Graduation       Divorced  46310.0
24        1960      Master       Together  17144.0
25        1958  Graduation        Married  65148.0
35        1987  Graduation        Married  25545.0

<div align="right">
<a href="#indice"><font size=5 color=#B51700><i class="fa fa-arrow-circle-up" aria-hidden="true" ></i></font></a>
</div>



---

<a id="section7"></a>
## <font color="#5E5E5E" size=5> 7. Operaciones sobre elementos: transformación </font>

<a id="section71"></a> 
### <font color="#5E5E5E">7.1 Operaciones sobre *Series*: vectorización</font>

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 22</font> 

Crear una *Serie* denominada  `s_income_m` con los valores de la columna `Income` del *DataFrame* expresados en miles de dólares, es decir, dividiendo el valor entre 1000.

In [142]:
s_income_m = df_marketing["Income"].div(1000)
s_income_m

ID
5524     58.138
2174     46.344
4141     71.613
6182     26.646
5324     58.293
          ...
10870    61.223
4001     64.014
7270     56.981
8235     69.245
9405     52.869
Name: Income, Length: 2240, dtype: float64

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 23</font> 

Crear una *Serie* denominada  `s_income_m` con los valores de la columna `Income` del *DataFrame* expresados en miles de dólares y en formato texto: dividiendo el valor entre 1000, transformándolo en un `string` y anadiéndole al final ` m $`.

In [143]:
s_income_m = df_marketing["Income"].div(1000).round(2).astype(str) + "$"
s_income_m

ID
5524     58.14$
2174     46.34$
4141     71.61$
6182     26.65$
5324     58.29$
          ...
10870    61.22$
4001     64.01$
7270     56.98$
8235     69.24$
9405     52.87$
Name: Income, Length: 2240, dtype: str



<a id="section72"></a> 
### <font color="#5E5E5E">7.2 Operaciones vectorizadas sobre *Series* de *Strings*: `Series.str`</font>

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 24</font> 

Transformar los valores de la columna `Marital_Status` del *DataFrame* `df_marketing` a minúscula. Asignar la *Serie* resultante a la propia columna y mostrar la cabecera de `df_marketing`.

In [155]:
df_marketing["Marital_Status"] = df_marketing["Marital_Status"].apply(lambda x: x.upper() if isinstance(x, str) else x)
df_marketing.head()

,index,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response
ID,,,,,,,,,,,,,,,,,,,,,
5524,0,1957,Graduation,SINGLE,58138.0,0,0,04-09-2012,58,635.0,...,10,4,7,0,0,0,0,0,0,1
2174,1,1954,Graduation,SINGLE,46344.0,1,1,08-03-2014,38,11.0,...,1,2,5,0,0,0,0,0,0,0
4141,2,1965,Graduation,TOGETHER,71613.0,0,0,21-08-2013,26,426.0,...,2,10,4,0,0,0,0,0,0,0
6182,3,1984,Graduation,TOGETHER,26646.0,1,0,10-02-2014,26,11.0,...,0,4,6,0,0,0,0,0,0,0
5324,4,1981,PhD,MARRIED,58293.0,1,0,19-01-2014,94,173.0,...,3,6,5,0,0,0,0,0,0,0

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 25</font> 

Utilizar `Series.str.extract()` para descomponer la fecha almacenada en la columna `Dt_Customer` del *DataFrame* `df_marketing` en tres columnas; `Day`, `Month` y `Year`.

In [160]:
regex = (r'(?P<Day>\d+)-(?P<Month>\d+)-(?P<Year>\d+)')
df_marketing["Dt_Customer"].str.extract(regex, expand=True)

      Day Month  Year
ID
5524   04    09  2012
2174   08    03  2014
4141   21    08  2013
6182   10    02  2014
5324   19    01  2014
...    ..   ...   ...
10870  13    06  2013
4001   10    06  2014
7270   25    01  2014
8235   24    01  2014
9405   15    10  2012

[2240 rows x 3 columns]

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 26</font> 

Repetir el ejercicio anterior, pero convirtiendo las columnas resultantes a enteros con `DataFrame.astype('int64')`, y asignando el resultado a nuevas columnas del *DataFrame* `df_marketing` denominadas `Day`, `Month` y `Year`.

In [176]:
df_marketing[["Day", "Month", "Year"]] = df_marketing["Dt_Customer"].str.extract(regex, expand=True).astype({"Day": "int64", "Month": "int64", "Year": "int64"})



<a id="section73"></a> 
### <font color="#5E5E5E">7.3 Operaciones de transformación sobre *Series*</font>

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 27</font> 

Crear una nueva columna denominada `Season` en el *DataFrame* `df_marketing`, y a partir de la columna `Month`, de modo que el valor de `Season` sea: `Winter` para los meses 1 a 3; `Spring` para los meses 4 a 6; `Summer` para los meses 5 a 9; y `Autumn` para los meses 10 a 12. Utilizar un diccionario para definir las transformarciones.

In [183]:
season_dict = {1: 'Winter', 2: 'Winter', 3:'Winter', 
               4: 'Spring', 5: 'Spring', 6: 'Spring', 
               7: 'Summer', 8: 'Summer', 9: 'Summer',
               10: 'Autumn',11:'Autumn', 12: 'Autumn'}

df_marketing["Season"] = df_marketing["Month"].map(season_dict)
df_marketing["Season"]

ID
5524     Summer
2174     Winter
4141     Summer
6182     Winter
5324     Winter
          ...
10870    Spring
4001     Spring
7270     Winter
8235     Winter
9405     Autumn
Name: Season, Length: 2240, dtype: str

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 28</font> 

Repetir el ejercicio anterior, pero utilizando `Series.apply()`.

In [184]:
def get_season(month):
    if month<4:
        return 'Winter'
    elif month<7:
        return 'Spring'
    elif month<10:
        return 'Summer'
    else:
        return 'Winter'
    

df_marketing["Season"] = df_marketing["Month"].apply(lambda x: get_season(x))
df_marketing["Season"]

ID
5524     Summer
2174     Winter
4141     Summer
6182     Winter
5324     Winter
          ...
10870    Spring
4001     Spring
7270     Winter
8235     Winter
9405     Winter
Name: Season, Length: 2240, dtype: str

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 29</font> 


A partir de la columna `Month` del *DataFrame* `df_marketing`, generar un nuevo *DataFrame* con dos columnas, de modo que la primera de ella contenga el nombre del mes correspondiente, y la segunda la estación. Utilizar una función *lambda* para acceder al nombre del mes.

In [196]:
months = ['January', 'February','March',
          'April','May','June',
          'July','August','September',
          'October','November','December']

df_marketing_nuevo = df_marketing[["Month", "Season"]]

df_marketing_nuevo["Month"] = df_marketing_nuevo["Month"].apply(lambda x: months[x-1])
df_marketing_nuevo

           Month  Season
ID
5524   September  Summer
2174       March  Winter
4141      August  Summer
6182    February  Winter
5324     January  Winter
...          ...     ...
10870       June  Spring
4001        June  Spring
7270     January  Winter
8235     January  Winter
9405     October  Winter

[2240 rows x 2 columns]



<a id="section74"></a> 
### <font color="#5E5E5E">7.4 Operaciones de transformación sobre *DataFrames*</font>

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 30</font> 


Crear un nuevo *DataFrame* a partir `df_marketing` que contenga todas las columnas que *no* son numéricas, pero transformadas a mayúsculas.

In [201]:
df_marketing_not_numeric_upper = df_marketing.select_dtypes(exclude=[np.number]).apply(lambda x: x.upper() if isinstance(x, str) else x)
df_marketing_not_numeric_upper

        Education Marital_Status Dt_Customer  Season
ID
5524   Graduation         SINGLE  04-09-2012  Summer
2174   Graduation         SINGLE  08-03-2014  Winter
4141   Graduation       TOGETHER  21-08-2013  Summer
6182   Graduation       TOGETHER  10-02-2014  Winter
5324          PhD        MARRIED  19-01-2014  Winter
...           ...            ...         ...     ...
10870  Graduation        MARRIED  13-06-2013  Spring
4001          PhD       TOGETHER  10-06-2014  Spring
7270   Graduation       DIVORCED  25-01-2014  Winter
8235       Master       TOGETHER  24-01-2014  Winter
9405          PhD        MARRIED  15-10-2012  Winter

[2240 rows x 4 columns]

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 31</font> 


Repetir el ejercicio anterior, pero transformando `Marital_Status` a mayúsculas, y `Season` a minúsculas.

In [204]:
df_marketing_not_numeric_upper = df_marketing.select_dtypes(exclude=[np.number]).apply(lambda x: x.str.upper() if x.name == "Marital_Status" else x.str.lower()  if  x.name == "Season" else x )
df_marketing_not_numeric_upper

        Education Marital_Status Dt_Customer  Season
ID
5524   Graduation         SINGLE  04-09-2012  summer
2174   Graduation         SINGLE  08-03-2014  winter
4141   Graduation       TOGETHER  21-08-2013  summer
6182   Graduation       TOGETHER  10-02-2014  winter
5324          PhD        MARRIED  19-01-2014  winter
...           ...            ...         ...     ...
10870  Graduation        MARRIED  13-06-2013  spring
4001          PhD       TOGETHER  10-06-2014  spring
7270   Graduation       DIVORCED  25-01-2014  winter
8235       Master       TOGETHER  24-01-2014  winter
9405          PhD        MARRIED  15-10-2012  winter

[2240 rows x 4 columns]

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 32</font> 

Crear una columna denominada `MntTotal` que contenga la suma de `MntWines`, `MntFruits`, `MntMeatProducts`, `MntFishProducts`, `MntSweetProducts` y `MntGoldProds`. Utilizar operaciones vectorizadas.

In [205]:
df_marketing["MntTotal"] = df_marketing[["MntWines", "MntFruits", "MntMeatProducts", "MntFishProducts", "MntSweetProducts", "MntGoldProds"]].sum(axis=1)
df_marketing

,index,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Day,Month,Year,Season,MntTotal
ID,,,,,,,,,,,,,,,,,,,,,
5524,0,1957,Graduation,SINGLE,58138.0,0,0,04-09-2012,58,635.0,...,0,0,0,0,1,4,9,2012,Summer,1617.0
2174,1,1954,Graduation,SINGLE,46344.0,1,1,08-03-2014,38,11.0,...,0,0,0,0,0,8,3,2014,Winter,27.0
4141,2,1965,Graduation,TOGETHER,71613.0,0,0,21-08-2013,26,426.0,...,0,0,0,0,0,21,8,2013,Summer,776.0
6182,3,1984,Graduation,TOGETHER,26646.0,1,0,10-02-2014,26,11.0,...,0,0,0,0,0,10,2,2014,Winter,53.0
5324,4,1981,PhD,MARRIED,58293.0,1,0,19-01-2014,94,173.0,...,0,0,0,0,0,19,1,2014,Winter,422.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10870,2235,1967,Graduation,MARRIED,61223.0,0,1,13-06-2013,46,709.0,...,0,0,0,0,0,13,6,2013,Spring,1341.0
4001,2236,1946,PhD,TOGETHER,64014.0,2,1,10-06-2014,56,406.0,...,0,1,0,0,0,10,6,2014,Spring,444.0
7270,2237,1981,Graduation,DIVORCED,56981.0,0,0,25-01-2014,91,908.0,...,0,0,0,0,0,25,1,2014,Winter,1241.0
8235,2238,1956,Master,TOGETHER,69245.0,0,1,24-01-2014,8,428.0,...,0,0,0,0,0,24,1,2014,Winter,843.0
9405,2239,1954,PhD,MARRIED,52869.0,1,1,15-10-2012,40,84.0,...,0,0,0,0,1,15,10,2012,Winter,172.0

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 33</font> 

Repetir el ejercicio anterior, pero utilizando `DataFrame.apply()`.

In [206]:
df_marketing["MntTotal"] = df_marketing.apply(lambda row: row["MntWines"] + row["MntFruits"] + row["MntMeatProducts"] + row["MntFishProducts"] + row["MntSweetProducts"] + row["MntGoldProds"], axis=1)
df_marketing

,index,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Day,Month,Year,Season,MntTotal
ID,,,,,,,,,,,,,,,,,,,,,
5524,0,1957,Graduation,SINGLE,58138.0,0,0,04-09-2012,58,635.0,...,0,0,0,0,1,4,9,2012,Summer,1617.0
2174,1,1954,Graduation,SINGLE,46344.0,1,1,08-03-2014,38,11.0,...,0,0,0,0,0,8,3,2014,Winter,27.0
4141,2,1965,Graduation,TOGETHER,71613.0,0,0,21-08-2013,26,426.0,...,0,0,0,0,0,21,8,2013,Summer,776.0
6182,3,1984,Graduation,TOGETHER,26646.0,1,0,10-02-2014,26,11.0,...,0,0,0,0,0,10,2,2014,Winter,53.0
5324,4,1981,PhD,MARRIED,58293.0,1,0,19-01-2014,94,173.0,...,0,0,0,0,0,19,1,2014,Winter,422.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10870,2235,1967,Graduation,MARRIED,61223.0,0,1,13-06-2013,46,709.0,...,0,0,0,0,0,13,6,2013,Spring,1341.0
4001,2236,1946,PhD,TOGETHER,64014.0,2,1,10-06-2014,56,406.0,...,0,1,0,0,0,10,6,2014,Spring,444.0
7270,2237,1981,Graduation,DIVORCED,56981.0,0,0,25-01-2014,91,908.0,...,0,0,0,0,0,25,1,2014,Winter,1241.0
8235,2238,1956,Master,TOGETHER,69245.0,0,1,24-01-2014,8,428.0,...,0,0,0,0,0,24,1,2014,Winter,843.0
9405,2239,1954,PhD,MARRIED,52869.0,1,1,15-10-2012,40,84.0,...,0,0,0,0,1,15,10,2012,Winter,172.0

<div align="right">
<a href="#indice"><font size=5 color=#B51700><i class="fa fa-arrow-circle-up" aria-hidden="true" ></i></font></a>
</div>



---

<a id="section8"></a>
# <font color="#5E5E5E" size=5> 8. Operaciones sobre conjuntos de elementos: Agregación </font>



<a id="section81"></a> 
### <font color="#5E5E5E">8.1 Funciones resumen y estadísticas en *Series*</font>

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 34</font> 



Mostrar los valores únicos y el número de veces que aparece cada uno en la columna `Education`. Considerar también los valores `NaN`.

In [226]:
df_marketing["Education"].value_counts(dropna=False)

Education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 35</font> 


Obtener la media de la columna `Income` calculando primero su suma, y dividiendo entre su tamaño.

In [237]:
media = df_marketing["Income"].sum()/df_marketing["Income"].count()
media_m = df_marketing["Income"].mean()
print("Media calculada manualmente:", media)
print("Media calculada con mean():", media_m)

Media calculada manualmente: 52247.25135379061
Media calculada con mean(): 52247.25135379061

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 36</font> 


Mostrar ahora la media y la desviación estándard de la columna `Income` utilizando para ello los métodos que implementa *Series*.

In [239]:
media_m = df_marketing["Income"].mean()
print("Media:", media)
desviacion_estandar = df_marketing["Income"].std()
print("Desviación estándar:", desviacion_estandar)

Media: 52247.25135379061
Desviación estándar: 25173.076660901403

<div class="alert alert-block alert-info">
    
<i class="fa fa-info-circle" aria-hidden="true"></i> Esta diferencia se debe a que los métodos `Series.mean()` y `Series.std()` como otros muchos, descartan los valores `NaN`.
</div>



<a id="section82"></a> 
### <font color="#5E5E5E">8.2 Funciones resumen en *DataFrames*</font>

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 37</font> 


Crear una columna denominada `MntMedia` que contenga la media de `MntWines`, `MntFruits`, `MntMeatProducts`, `MntFishProducts`, `MntSweetProducts` y `MntGoldProds`.

In [241]:
mnt_colums = ['MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']

df_marketing["MntMedia"] = df_marketing[mnt_colums].mean(axis=1)

df_marketing["MntMedia"]

ID
5524     269.500000
2174       4.500000
4141     129.333333
6182       8.833333
5324      70.333333
            ...
10870    223.500000
4001      74.000000
7270     206.833333
8235     140.500000
9405      28.666667
Name: MntMedia, Length: 2240, dtype: float64

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 38</font> 


Mostrar las filas correspondientes a los 5 mayores valores de `Income`.

In [243]:
df_marketing["Income"].sort_values(ascending=False).head()

ID
9432    666666.0
1503    162397.0
1501    160803.0
5336    157733.0
8475    157243.0
Name: Income, dtype: float64



<a id="section83"></a> 
### <font color="#5E5E5E">8.3 Agregación en *Series* y *DataFrames*</font>

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 39</font> 


Obtener, con una sola orden, la media,  desviación y suma de la columna `Income`. Indexar los elementos resultantes utilizando las etiquetas `Media`, `Desviación` y `Suma` respectivamente.

In [245]:
media, desviacion_estandar, suma = df_marketing["Income"].mean(), df_marketing["Income"].std(), df_marketing["Income"].sum()
print("Media:", media)
print("Desviación estándar:", desviacion_estandar)
print("Suma:", suma)

Media: 52247.25135379061
Desviación estándar: 25173.076660901403
Suma: 115779909.0

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 40</font> 

Utilizando una sola orden, obtener la media y desviación para todas las columnas en `mnt_columns`.

In [246]:
mnt_colums = ['MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']

media, desviacion_estandar = df_marketing[mnt_colums].mean(), df_marketing[mnt_colums].std()

print("Media de las columnas de gasto:", media)
print("Desviación estándar de las columnas de gasto:", desviacion_estandar)

Media de las columnas de gasto: MntWines            303.935714
MntFruits            26.302232
MntMeatProducts     166.950000
MntFishProducts      37.525446
MntSweetProducts     27.062946
MntGoldProds         44.021875
dtype: float64
Desviación estándar de las columnas de gasto: MntWines            336.597393
MntFruits            39.773434
MntMeatProducts     225.715373
MntFishProducts      54.628979
MntSweetProducts     41.280498
MntGoldProds         52.167439
dtype: float64

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 41</font> 

Repetir el ejercicio anterior, pero utilizando `DataFrame.apply()`. Para ello, la función pasada como argumento debe devolver una tupla por cada columna.

In [247]:
media, desviacion_estandar = df_marketing[mnt_colums].apply(np.mean), df_marketing[mnt_colums].apply(np.std)

print("Media de las columnas de gasto:", media)
print("Desviación estándar de las columnas de gasto:", desviacion_estandar)

Media de las columnas de gasto: MntWines            303.935714
MntFruits            26.302232
MntMeatProducts     166.950000
MntFishProducts      37.525446
MntSweetProducts     27.062946
MntGoldProds         44.021875
dtype: float64
Desviación estándar de las columnas de gasto: MntWines            336.522251
MntFruits            39.764555
MntMeatProducts     225.664984
MntFishProducts      54.616784
MntSweetProducts     41.271283
MntGoldProds         52.155793
dtype: float64

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 42</font> 

Utilizar ahora `DataFrame.apply()` para obtener la media de las columnas en `mnt_colums` para cada fila.

In [250]:
media =  df_marketing.apply(lambda x: x.mean() if x.name in mnt_colums else None)

print("Media de las columnas de gasto:", media)

Media de las columnas de gasto: index                         NaN
Year_Birth                    NaN
Education                     NaN
Marital_Status                NaN
Income                        NaN
Kidhome                       NaN
Teenhome                      NaN
Dt_Customer                   NaN
Recency                       NaN
MntWines               303.935714
MntFruits               26.302232
MntMeatProducts        166.950000
MntFishProducts         37.525446
MntSweetProducts        27.062946
MntGoldProds            44.021875
NumDealsPurchases             NaN
NumWebPurchases               NaN
NumCatalogPurchases           NaN
NumStorePurchases             NaN
NumWebVisitsMonth             NaN
AcceptedCmp3                  NaN
AcceptedCmp4                  NaN
AcceptedCmp5                  NaN
AcceptedCmp1                  NaN
AcceptedCmp2                  NaN
Complain                      NaN
Response                      NaN
Day                           NaN
Month                         NaN
Year                          NaN
Season                        NaN
MntTotal                      NaN
MntMedia                      NaN
dtype: float64

<div align="right">
<a href="#indice"><font size=5 color=#B51700><i class="fa fa-arrow-circle-up" aria-hidden="true" ></i></font></a>
</div>




---


## <font color="#5E5E5E">Otros</font>

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 43</font> 

Devolver los 5 clientes (5 filas) cuya suma de gastos (columnas en `mnt_coluns`) es mayor.

In [257]:

df_marketing.sort_values(by="MntTotal", ascending=False).head(5)

,index,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp1,AcceptedCmp2,Complain,Response,Day,Month,Year,Season,MntTotal,MntMedia
ID,,,,,,,,,,,,,,,,,,,,,
5350,1572,1991,Master,SINGLE,90638.0,0,0,13-02-2014,29,1156.0,...,0,0,0,1,13,2,2014,Winter,2525.0,420.833333
5735,1179,1991,Master,SINGLE,90638.0,0,0,13-02-2014,29,1156.0,...,0,0,0,0,13,2,2014,Winter,2525.0,420.833333
1763,1492,1988,Graduation,TOGETHER,87679.0,0,0,27-07-2013,62,1259.0,...,1,0,0,1,27,7,2013,Summer,2524.0,420.666667
4580,987,1969,Graduation,MARRIED,75759.0,0,0,25-10-2013,46,1394.0,...,1,0,0,1,25,10,2013,Winter,2486.0,414.333333
4475,1052,1949,PhD,MARRIED,69098.0,0,0,16-02-2013,82,1315.0,...,0,0,0,0,16,2,2013,Winter,2440.0,406.666667

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 44</font> 

Calcular el *Z-score* de la columna `Income` de cada cliente. Es decir, cuántas desviaciones estándar por encima o debajo de la media están los ingresos.

In [258]:
df_marketing["Z_Score"] = (df_marketing["MntTotal"] - df_marketing["MntTotal"].mean()) / df_marketing["MntTotal"].std()
df_marketing["Z_Score"]

ID
5524     1.679042
2174    -0.961061
4141     0.282610
6182    -0.917889
5324    -0.305186
           ...
10870    1.220760
4001    -0.268657
7270     1.054716
8235     0.393860
9405    -0.720297
Name: Z_Score, Length: 2240, dtype: float64

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 45</font> 

Calcular el porcentaje de dinero que gasta cada cliente (suma de las columnas en `mnt_columns`) con respecto a sus ingresos. Utilizar para ello `DataFrame.apply()`

In [259]:
df_marketing["Porcentaje_Gasto"] = df_marketing.apply(lambda row: (row["MntTotal"] / row["Income"]) * 100 if row["Income"] > 0 else 0, axis=1)
df_marketing["Porcentaje_Gasto"]

ID
5524     2.781313
2174     0.058260
4141     1.083602
6182     0.198904
5324     0.723929
           ...
10870    2.190353
4001     0.693598
7270     2.177919
8235     1.217416
9405     0.325332
Name: Porcentaje_Gasto, Length: 2240, dtype: float64

### <font size=3 color="#5E5E5E"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#5E5E5E"></i> Ejercicio 46</font> 

Calcular la media y desviación de los del 50% de los clientes que tienen un mayor salario.

In [260]:
salarios = df_marketing["Income"].sort_values(ascending=False)

top_50 = salarios.head(len(salarios) // 2)

media = top_50.mean()
desviacion = top_50.std()

print("Media:", media)
print("Desviación estándar:", desviacion)

Media: 70165.97678571429
Desviación estándar: 22150.587314524426

<br>
<div align="right">
<a href="#inicio"><font size=5 color="#B51700"><i class="fa fa-arrow-circle-up" aria-hidden="true"></i></font></a>
</div>

---

<div align="right">
<font size=5 color="#B51700"><i class="fa fa-coffee" aria-hidden="true"></i></font>
</div>